### ISSUE TITLE
mouse left doesn't work anymore i guess

### ISSUE THREAD

**Issue by merts1** [Leaf48/ValorantTriggerBot#1]
do you know any method to use mouse left rn because I've been using this but it is not available anymore

**Comment by Leaf48** [comment]
What does "rn" mean?

Thanks

**Comment by merts1** [comment]
acronym for "right now"

anyway, I have a different but similar code to this one here that I've been using to create a dataset of valorant agent recognition algorithm based on colormaps.

I guess riot disabled any external mouse input along with mouse movements right now. So I can't really know if the target selected is a real agent.

Which also means your code doesn't work in game from now on too.
